apiVersion: v1
kind: Service
metadata:
  name: deis-minio
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
spec:
  ports:
    - name: s3
      port: 9000
  selector:
    app: deis-minio
